# -*- coding: utf-8 -*-
"""Listas e Tuplas - Inversao de Lista

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZX9bynVmqBIWmz9ZNINxLNENTesyomiq
"""

# Desenvolva um algoritmo que leia um conjunto de 20 valores inteiros, guarde-os em uma lista e troque a sua ordem.
# Ou seja, o programa deve trocar lista[0] com lista[19], lista[1] com lista[18] e assim por diante.

# Entrada: Uma linha com 20 números inteiros.

# Saida: Os mesmos 20 números em ordem inversa, um por linha.

def main():

  lista = list(map(int,input().split()))

  for i in lista[::-1]:
    print(i)

if __name__ == "__main__":
  main()