# -*- coding: utf-8 -*-
"""Listas e Tuplas - Maior e menor palavra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2IAMAHVDqXHgeO2p81Duf_GVBU7tI-G
"""

# Desenvolva um algoritmo que leia uma frase e encontre a maior e a menor palavra nessa frase. 
# Imprima as palavras encontradas. Se houver mais de uma palavra com o menor ou maior tamanho, imprimir a primeira que aparece na frase.

# Entrada: Uma frase

# Saída: Duas linhas, a menor e a maior palavra, respectivamente

def maior_menor_palavra(frase):
  lista_maior = []
  lista_menor = []
  maior = ''
  menor = frase[0]

  for palavra in frase:

    if len(palavra) < len(menor):

      lista_menor = [palavra,]

      menor = palavra

    elif len(palavra) == len(menor):

      lista_menor.append(palavra)

    else:

      if len(palavra) > len(maior):

        lista_maior = [palavra,]

        maior = palavra

      elif len(palavra) == len(maior):

        lista_maior.append(palavra)

  return (lista_maior, lista_menor)


def main():

  frase = input().split()

  maior,menor = maior_menor_palavra(frase)

  if (len(maior) == 0):

    print(menor[0])
    print(menor[0])
  
  else:
    print(menor[0])
    print(maior[0])

if __name__ == "__main__":
  main()