# -*- coding: utf-8 -*-
"""Listas e Tuplas - Produto escalar de 2 vetores

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148CYp7mVkSW4wjyAFib9Mp27vUKSBsYe
"""

# Dados dois vetores x e y, ambos com n elementos, determinar o produto escalar desses vetores. Exemplo: Produto escalar de x=(3,4) e y=(-2,5) é: x.y = 3.(-2) + 4.(5) = -6+20 = 14.

# A entrada terá 3 linhas: a primeira indicando o tamanho dos vetores, a segunda com os elementos do primeiro vetor e a terceira com os elementos do segundo vetor.

# Entrada: Um inteiro N. Em seguida, 2 linhas, cada uma contendo as N coordenadas de cada vetor.

# Saída: O produto escalar entre esses vetores, formatado com 2 casas decimais

# Nota: A saída deve apresentar duas casas decimais, como no exemplo abaixo.

def produto_escalar(v1,v2,tamanho):

  prod = 0

  for i in range(tamanho):

    prod += v1[i]*v2[i]

  return prod

def main():
  tamanho_vet = int(input())

  v1 = list(map(float, input().split()))

  v2 = list(map(float, input().split()))

  resultado_prod = produto_escalar(v1,v2,tamanho_vet)

  print(f"{resultado_prod:.2f}")

if __name__ == "__main__":

  main()